{% set version = "0.2-22" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cba
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cba_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cba/cba_{{ version }}.tar.gz
  sha256: f1dc8993f7b41b5bf3258939fb4c9eda5fda0b08f5026727245fd2d3fcbc9040

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-proxy
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-proxy

test:
  commands:
    - $R -e "library('cba')"           # [not win]
    - "\"%R%\" -e \"library('cba')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cba
  license: GPL-2.0-only
  summary: 'Implements clustering techniques such as Proximus and Rock, utility functions for efficient computation of cross distances and data manipulation. '
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: cba
# Type: Package
# Title: Clustering for Business Analytics
# Version: 0.2-21
# Author: Christian Buchta and Michael Hahsler
# Maintainer: Christian Buchta <christian.buchta@wu.ac.at>
# Description: Implements clustering techniques such as Proximus and Rock, utility functions for efficient computation of cross distances and data manipulation.
# Depends: R (>= 2.10), grid, proxy
# Imports: stats, graphics, grDevices, methods
# Suggests: gclus, colorspace
# Encoding: latin1
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-04-18 15:33:05 UTC; hornik
# Repository: CRAN
# Date/Publication: 2019-04-18 15:46:59 UTC
