travis:
  secure:
    BINSTAR_TOKEN: 2h1VK/jdzDsNyQeEC3Mc45gA9nloLFCBiIbElY3RELmtuWoaNJs5p8/2rneYcFkpdHe4iipEmD3bMR955KopO7hmUbZnIw7m7Q8/9Vs8xDaKR60UQbdjqT6eUIgsCaHGb7DSFrTjJLR6MFDcyTHzEE+zB3pfjWR3DRKZ/VZeXoa6Egy1ZcMEjXfdHDrR9Fv8x9KKCz576VckdPfqiECEoyEKAkV35J53tcROHkW2PhiMhd1n+EGkV+wawDyGQv9Cj43ti/qgd33qHr6kth2NlMffgR+L54BIAeI2JLSHUBiKySpcq6l5Jq9wjTkX9ekRdmvMsMd7420I7Ba4gr93YpRmqzSYbIupHS4FXzExfWNFye11GrX6tV3sZAZD/OqNJGLEiQiOxVyT4Tz0KTiIgqgZn3bhqdziMR1jy0xngrPlWzndChlLYlz6+tWo49Px0enB2nm/CSuOX1UCMu0j9Sv47gunwrPrh22D5hMgKvI0j0Sr11+FLP568P7PZj9KojXww5vMEynm9L0VyE8w/fNspQptjXncBxgGbwWCdVPkhz0IFhlLUzEE36MSMZmrtr+Sg8LLwricXFoeSW8LWLXfCxNUYR0ub90D4lIkRyEwRabPDdcEMqYKwbmbCyCEFSQpR9fha0lGorwrvNMoZAaPhToKjuVlyUqp1NkRAd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
