travis:
  secure:
    BINSTAR_TOKEN: V0EoBKbKPsXSTg7pTyuIkDkSg8HmiS/9RoGEZEsD9ZSDLjnmOOMFcKZmZG5mITMOe+JXEDi0m7qNkSt9qkxAQIZBP18Qggek/X8Hr4U46TNMaCZUqxQcxPibTQYnrPdXSwAzCeoAro9ZKQmxrXzbYur7BJYQHV7QqnTfB5FaCLDhtzznfNBIvyahdRGyCgzR6KD+RDnt8iYJYaFfr52SmLASoyBKmMPTMwOD9vtfA6Hwr7xZ6qYBuTvugf1N9zNQcU9vq9w9bbkQ+7YB3ZAh1/MVKbK6twzRkWR+Z5uEZY3zi6HObCASogNE5bXJCcjTeS5jGJY/wlzYxA0Hqh5wN5WHtpEc/WQ+odFOHJU+tDnhEEdMMB4XCP/s+TSoq+WdLA8kRV6uzjkeYuCTy0yHugYUNfX0CLlF8gEJpQW5DQr0gQ6Gwk39+WxHHKX+cqA+DE0kHHxfh6jtcV7QkfR+ia+r3cpUx7G1DfJo1DHxYI5NVodaX5Jnyq53hW0MDeJn3CeCpKTqleVeYA0pp+WVn4swzTFQywXdWWb7mJRfKqlbWzsuzXykjSgZu8nsrvE23fB+idIQhfP7AZsNfNzuhONYvkPHZaUiiAqbinVWy/aBKImL7zYvWcfEpqNCS4MPtVbvBlV0hh+wPFGcvNu8PBsIVnlVTLgI9LYGjGbNnz0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
